# Use the official Golang image as the base image
FROM golang:latest
# Set the Current Working Directory inside the container
WORKDIR /app
# Copy the current directory contents into the container at /app
COPY . .
# Build the Go program in the /examples directory
RUN go build -o /usr/local/bin/examples ./examples
EXPOSE 47808

# docker run --rm --name jonalfarlinga-bacnet -p 47808:47808 --network host -it $(docker build -q -f Dockerfile.rpc .) /bin/bash
